#!/usr/bin/env python3

import argparse
import os
import boto3

def main(profile_name, cmd, region):
	env = os.environ.copy()
	if profile_name != 'env':
		session = boto3.session.Session(profile_name=profile_name)
		credentials = session.get_credentials().get_frozen_credentials()
		env['AWS_ACCESS_KEY_ID']     = credentials.access_key
		env['AWS_SECRET_ACCESS_KEY'] = credentials.secret_key
		if credentials.token:
			env['AWS_SESSION_TOKEN'] = credentials.token
	if region:
		env['AWS_DEFAULT_REGION'] = region
	os.execvpe(
		cmd[0],
		cmd,
		env,
	)

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='Run command with AWS credentials in environment.')
	parser.add_argument('--profile', type=str, default='default',
		help='select the profile credentials will be obtained for',
	)
	parser.add_argument('--region', type=str,
		help='the default AWS region',
	)
	parser.add_argument('cmd', type=str, metavar='cmd',
		help='program to be run with AWS credentials',
	)
	parser.add_argument('args', type=str, metavar='arg', nargs='*',
		help='arguments to the program',
	)
	args = parser.parse_args()
	cmd = [args.cmd] + args.args
	main(args.profile, cmd, args.region)

# vim: set ts=4 sts=4 noet:
